### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by harikt** [edumeet/edumeet-docker#27]
I have cloned the repo 

1. git clone https://github.com/edumeet/edumeet-docker/
2. Added turn servers to : configs/server/config.js
3. docker-compose pull
4. docker-compose up --detach

At certain point it exists with the below error.

```
...
...
> edumeet@3.4.0 build /projects/edumeet/code/edumeet/app
> react-scripts build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/

Creating an optimized production build...
Failed to compile.

src/components/Containers/Me.js
  Line 502:45:  Unexpected use of comma operator  no-sequences
  Line 565:45:  Unexpected use of comma operator  no-sequences

Search for the keywords to learn more about each error.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edumeet@3.4.0 build: `react-scripts build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edumeet@3.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-02T09_24_14_618Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
ERROR: Service 'edumeet' failed to build : Build failed
```

If I run `docker-compose ps` , it shows 

```
code_edumeet_1   /docker-entrypoint.sh            Restarting
```

**Comment by harikt** [comment]
After running without detached mode I noticed the error 


```
code_edumeet_1 exited with code 1
edumeet_1    | - process.env.DEBUG: undefined
edumeet_1    | - config.mediasoup.worker.logLevel: warn
edumeet_1    | - config.mediasoup.worker.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp' ]
edumeet_1    | fs.js:114
edumeet_1    |     throw err;
edumeet_1    |     ^
edumeet_1    |
edumeet_1    | Error: ENOENT: no such file or directory, open '/opt/edumeet/server/config/../certs/key.pem'
edumeet_1    |     at Object.openSync (fs.js:443:3)
edumeet_1    |     at Object.readFileSync (fs.js:343:35)
edumeet_1    |     at Object.<anonymous> (/opt/edumeet/server/server.js:71:21)
edumeet_1    |     at Module._compile (internal/modules/cjs/loader.js:778:30)
edumeet_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
edumeet_1    |     at Module.load (internal/modules/cjs/loader.js:653:32)
edumeet_1    |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
edumeet_1    |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
edumeet_1    |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
edumeet_1    |     at startup (internal/bootstrap/node.js:283:19)

```

But the key generated via command

```
openssl req -x509 -newkey rsa:4096 -keyout privkey.pem -out cert.pem -days 365 -nodes
```

was `privkey.pem`, but required `key.pem` .
